# Generated by Django 4.1.3 on 2022-11-20 13:43

import creditcards.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('cc_holder_name', models.CharField(max_length=200)),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, null=True, verbose_name='card number')),
                ('cc_exp_month', models.CharField(choices=[('Month', 'Month'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=25)),
                ('cc_exp_year', models.CharField(choices=[('Year', 'Year'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=25)),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, null=True, verbose_name='security code')),
            ],
        ),
    ]
