# Generated by Django 4.1.3 on 2022-11-24 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscribedusers_alter_myuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedusers',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 24, 14, 59, 50, 789738, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
